import { prisma } from '@intellifinance/database';
import { queueService } from '../../services/queue.service';
import { uploadService, GraphQLUploadFile } from '../../services/upload.service';
// IngestionStatus is generated by Prisma
import { IngestionStatus } from '@prisma/client';

export const ingestionResolvers = {
  Mutation: {
    uploadStatement: async (_: any, { file, accountId }: { file: Promise<GraphQLUploadFile>, accountId: string }) => {
      // 1. Save file
      const filePath = await uploadService.saveFile(file);

      // 2. Create Job in DB
      const job = await prisma.ingestionJob.create({
        data: {
          accountId,
          fileUrl: filePath,
          status: IngestionStatus.PENDING,
        },
        include: {
          account: {
            include: {
              transactions: true
            }
          }
        }
      });

      // 3. Dispatch to Queue
      await queueService.addIngestionJob({
        jobId: job.id,
        fileUrl: filePath,
        accountId,
      });

      return job;
    },
  },
  Query: {
    ingestionJob: async (_: any, { id }: { id: string }) => {
      return prisma.ingestionJob.findUnique({
        where: { id },
        include: {
          account: {
            include: {
              transactions: true
            }
          }
        }
      });
    },
  },
  Transaction: {
    amount: (parent: any) => {
      // Handle Prisma Decimal to GraphQL Float
      return parent.amount ? parseFloat(parent.amount.toString()) : 0;
    }
  }
};
