import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // IntelliFinance consolidated documentation structure
  docsSidebar: [
    'intro',
    'introducao',
    {
      type: 'category',
      label: '01 - SWEBOK Documentation',
      items: [{type: 'autogenerated', dirName: '01-swebok'}],
    },
    {
      type: 'category',
      label: '02 - Development',
      items: [{type: 'autogenerated', dirName: '02-development'}],
    },
    {
      type: 'category',
      label: '03 - SDD Methodology',
      items: [{type: 'autogenerated', dirName: '03-sdd-methodology'}],
    },
    {
      type: 'category',
      label: '04 - AI Tools',
      items: [{type: 'autogenerated', dirName: '04-ai-tools'}],
    },
    {
      type: 'category',
      label: '05 - Knowledge Base',
      items: [{type: 'autogenerated', dirName: '05-knowledge-base'}],
    },
    {
      type: 'category',
      label: '06 - Project Meta',
      items: [{type: 'autogenerated', dirName: '06-project-meta'}],
    },
  ],
};

export default sidebars;
