import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a single sidebar for all content
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Project Documentation',
      items: [
        'introducao',
        {
          type: 'category',
          label: 'Software Requirements',
          items: [{type: 'autogenerated', dirName: '02-requisitos-software'}],
        },
        {
          type: 'category',
          label: 'Software Design',
          items: [{type: 'autogenerated', dirName: '03-design-software'}],
        },
        {
          type: 'category',
          label: 'Software Construction',
          items: [{type: 'autogenerated', dirName: '04-construcao-software'}],
        },
        {
          type: 'category',
          label: 'Software Testing',
          items: [{type: 'autogenerated', dirName: '05-teste-software'}],
        },
        {
          type: 'category',
          label: 'Software Maintenance',
          items: [{type: 'autogenerated', dirName: '06-manutencao-software'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
    {
      type: 'category',
      label: 'AI-Assisted Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
        {
          type: 'autogenerated',
          dirName: 'sdd-workflow-guides',
        }
      ],
    },
    {
      type: 'category',
      label: 'Project Meta-Docs',
      items: [{type: 'autogenerated', dirName: 'project-meta'}],
    },
    {
      type: 'category',
      label: 'JIRA Issues',
      items: [{type: 'autogenerated', dirName: 'jira-issues'}],
    },
    {
      type: 'category',
      label: 'Analytics',
      items: [{type: 'autogenerated', dirName: 'analytics'}],
    },
  ],
};

export default sidebars;
