import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // JIRA Issues Sidebar - Auto-generated from jira-issues folder
  issuesSidebar: [
    {
      type: 'category',
      label: 'JIRA Issues',
      link: {
        type: 'doc',
        id: 'jira-issues/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'jira-issues'},
      ],
    },
  ],

  // Documentation Sidebar - Auto-generated from documentation folder
  documentationSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      link: {
        type: 'doc',
        id: 'documentation/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'documentation'},
      ],
    },
  ],

  // Development Sidebar - Auto-generated from development folder
  developmentSidebar: [
    {
      type: 'category',
      label: 'Development',
      link: {
        type: 'doc',
        id: 'development/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'development'},
      ],
    },
  ],

  // Analytics Sidebar - Auto-generated from analytics folder
  analyticsSidebar: [
    {
      type: 'category',
      label: 'Analytics',
      link: {
        type: 'doc',
        id: 'analytics/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'analytics'},
      ],
    },
  ],
};

export default sidebars;
